"""add remote servers

Revision ID: 92b2ce4b6c87
Revises: f6f695a38339
Create Date: 2022-01-03 01:20:39.066496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b2ce4b6c87'
down_revision = 'f6f695a38339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('last_sync_date', sa.DateTime(), nullable=True),
    sa.Column('paused', sa.Boolean(), nullable=True),
    sa.Column('endpoint', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remotes')
    # ### end Alembic commands ###
