"""add profile metadata ipfs and wow addy

Revision ID: c548cc54ee17
Revises: 40734564d415
Create Date: 2021-12-30 01:35:12.774067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c548cc54ee17'
down_revision = '40734564d415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memes', schema=None) as batch_op:
        batch_op.create_unique_constraint('memes_file_name_uniq', ['file_name'])

    with op.batch_alter_table('moderators', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ipfs_hash', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('wownero_address', sa.String(length=120), nullable=True))
        batch_op.drop_constraint('users_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('moderator_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moderator_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('users_user_id_fkey', 'moderators', ['moderator_id'], ['id'])
        batch_op.drop_column('wownero_address')
        batch_op.drop_column('ipfs_hash')

    with op.batch_alter_table('moderators', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('memes', schema=None) as batch_op:
        batch_op.drop_constraint('memes_file_name_uniq', type_='unique')

    # ### end Alembic commands ###
